// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.9
// source: common.proto

package wpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HFuncHttpRequestMethod int32

const (
	HFuncHttpRequestMethod_GET    HFuncHttpRequestMethod = 0
	HFuncHttpRequestMethod_POST   HFuncHttpRequestMethod = 1
	HFuncHttpRequestMethod_PUT    HFuncHttpRequestMethod = 2
	HFuncHttpRequestMethod_DELETE HFuncHttpRequestMethod = 3
)

// Enum value maps for HFuncHttpRequestMethod.
var (
	HFuncHttpRequestMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	HFuncHttpRequestMethod_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x HFuncHttpRequestMethod) Enum() *HFuncHttpRequestMethod {
	p := new(HFuncHttpRequestMethod)
	*p = x
	return p
}

// **************************
// *    plugin commons      *
// **************************
type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author          string                      `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description     string                      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl         string                      `protobuf:"bytes,6,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	PluginConstants map[string]string           `protobuf:"bytes,10,rep,name=plugin_constants,json=pluginConstants,proto3" json:"plugin_constants,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserAttributes  map[string]*PluginAttribute `protobuf:"bytes,15,rep,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PluginInfo) GetPluginConstants() map[string]string {
	if x != nil {
		return x.PluginConstants
	}
	return nil
}

func (x *PluginInfo) GetUserAttributes() map[string]*PluginAttribute {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

type PluginAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type        string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	VRule       string `protobuf:"bytes,8,opt,name=v_rule,json=vRule,proto3" json:"v_rule,omitempty"`
	VMsg        string `protobuf:"bytes,10,opt,name=v_msg,json=vMsg,proto3" json:"v_msg,omitempty"`
}

func (x *PluginAttribute) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginAttribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginAttribute) GetVRule() string {
	if x != nil {
		return x.VRule
	}
	return ""
}

func (x *PluginAttribute) GetVMsg() string {
	if x != nil {
		return x.VMsg
	}
	return ""
}

type HFuncHttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  HFuncHttpRequestMethod `protobuf:"varint,1,opt,name=method,proto3,enum=HFuncHttpRequestMethod" json:"method,omitempty"`
	Url     string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Body    string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params  map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HFuncHttpRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HFuncHttpRequest) GetMethod() HFuncHttpRequestMethod {
	if x != nil {
		return x.Method
	}
	return HFuncHttpRequestMethod_GET
}

func (x *HFuncHttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HFuncHttpRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HFuncHttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HFuncHttpRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type HFuncHttpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32             `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body       string            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers    map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HFuncHttpResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HFuncHttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HFuncHttpResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HFuncHttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HFuncLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *HFuncLogRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HFuncLogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}
