// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.9
// source: common.proto

package wpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **************************
// *        commons         *
// **************************
type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author          string                      `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description     string                      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl         string                      `protobuf:"bytes,6,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	PluginConstants map[string]string           `protobuf:"bytes,10,rep,name=plugin_constants,json=pluginConstants,proto3" json:"plugin_constants,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserAttributes  map[string]*PluginAttribute `protobuf:"bytes,15,rep,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PluginInfo) GetPluginConstants() map[string]string {
	if x != nil {
		return x.PluginConstants
	}
	return nil
}

func (x *PluginInfo) GetUserAttributes() map[string]*PluginAttribute {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

type PluginAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type        string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	VRule       string `protobuf:"bytes,8,opt,name=v_rule,json=vRule,proto3" json:"v_rule,omitempty"`
	VMsg        string `protobuf:"bytes,10,opt,name=v_msg,json=vMsg,proto3" json:"v_msg,omitempty"`
}

func (x *PluginAttribute) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginAttribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginAttribute) GetVRule() string {
	if x != nil {
		return x.VRule
	}
	return ""
}

func (x *PluginAttribute) GetVMsg() string {
	if x != nil {
		return x.VMsg
	}
	return ""
}
