// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.7
// source: CaptchaPlugin.proto

package pcaptcha

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	wpc "github.com/wshops/wshop-plugin-common/pkg/wpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyCaptchaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Captcha string `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
}

func (x *VerifyCaptchaRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *VerifyCaptchaRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type VerifyCaptchaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,2,opt,name=isValid,proto3" json:"isValid,omitempty"`
}

func (x *VerifyCaptchaResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *VerifyCaptchaResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type GetCustomHtmlInputFieldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Html string `protobuf:"bytes,20,opt,name=html,proto3" json:"html,omitempty"`
}

func (x *GetCustomHtmlInputFieldResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetCustomHtmlInputFieldResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type GetCustomHtmlHeadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Html string `protobuf:"bytes,20,opt,name=html,proto3" json:"html,omitempty"`
}

func (x *GetCustomHtmlHeadResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetCustomHtmlHeadResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type GetCustomHtmlBodyEndResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Html string `protobuf:"bytes,20,opt,name=html,proto3" json:"html,omitempty"`
}

func (x *GetCustomHtmlBodyEndResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetCustomHtmlBodyEndResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

// go:plugin type=plugin version=1
type Captcha interface {
	GetPluginInfo(context.Context, emptypb.Empty) (wpc.PluginInfo, error)
	// VerifyCaptcha 验证验证码
	VerifyCaptcha(context.Context, VerifyCaptchaRequest) (VerifyCaptchaResponse, error)
	// GetCustomHtmlInputField 获取自定义的html输入框
	GetCustomHtmlInputField(context.Context, emptypb.Empty) (GetCustomHtmlInputFieldResponse, error)
	// GetCustomHtmlHead 自定义 html 头部中需要加的内容
	GetCustomHtmlHead(context.Context, emptypb.Empty) (GetCustomHtmlHeadResponse, error)
	// GetCustomHtmlBodyEnd 自定义 html body 中最结尾需要加的内容
	GetCustomHtmlBodyEnd(context.Context, emptypb.Empty) (GetCustomHtmlBodyEndResponse, error)
}
