//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.7
// source: CaptchaPlugin.proto

package captcha

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const CaptchaPluginPluginAPIVersion = 1

//export captcha_plugin_api_version
func _captcha_plugin_api_version() uint64 {
	return CaptchaPluginPluginAPIVersion
}

var captchaPlugin CaptchaPlugin

func RegisterCaptchaPlugin(p CaptchaPlugin) {
	captchaPlugin = p
}

//export captcha_plugin_config_plugin_info
func _captcha_plugin_config_plugin_info(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req ConfigPluginInfoRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := captchaPlugin.ConfigPluginInfo(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//export captcha_plugin_verify_captcha
func _captcha_plugin_verify_captcha(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req VerifyCaptchaRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := captchaPlugin.VerifyCaptcha(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//export captcha_plugin_get_custom_html_input_field
func _captcha_plugin_get_custom_html_input_field(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req GetCustomHtmlInputFieldRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := captchaPlugin.GetCustomHtmlInputField(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//export captcha_plugin_get_custom_html_head
func _captcha_plugin_get_custom_html_head(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req GetCustomHtmlHeadRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := captchaPlugin.GetCustomHtmlHead(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//export captcha_plugin_get_custom_html_body_end
func _captcha_plugin_get_custom_html_body_end(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req GetCustomHtmlBodyEndRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := captchaPlugin.GetCustomHtmlBodyEnd(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
