// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.7
// source: VCodePlugin.proto

package pvcode

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendType int32

const (
	SendType_EMAIL SendType = 0
	SendType_SMS   SendType = 1
	SendType_OTHER SendType = 3
)

// Enum value maps for SendType.
var (
	SendType_name = map[int32]string{
		0: "EMAIL",
		1: "SMS",
		3: "OTHER",
	}
	SendType_value = map[string]int32{
		"EMAIL": 0,
		"SMS":   1,
		"OTHER": 3,
	}
)

func (x SendType) Enum() *SendType {
	p := new(SendType)
	*p = x
	return p
}

type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendType SendType `protobuf:"varint,1,opt,name=sendType,proto3,enum=pvcode.SendType" json:"sendType,omitempty"`
	Target   string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Code     string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SendVerificationCodeRequest) GetSendType() SendType {
	if x != nil {
		return x.SendType
	}
	return SendType_EMAIL
}

func (x *SendVerificationCodeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SendVerificationCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SendVerificationCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendVerificationCodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// **************************
// *        commons         *
// **************************
type ConfigPluginInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigPluginInfoRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string         `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string         `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version        string         `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Author         string         `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	Description    string         `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Icon           string         `protobuf:"bytes,6,opt,name=Icon,proto3" json:"Icon,omitempty"`
	UserAttributes []*PAttributes `protobuf:"bytes,7,rep,name=UserAttributes,proto3" json:"UserAttributes,omitempty"`
	PluginConstant []*PConstants  `protobuf:"bytes,8,rep,name=PluginConstant,proto3" json:"PluginConstant,omitempty"`
}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PluginInfo) GetUserAttributes() []*PAttributes {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *PluginInfo) GetPluginConstant() []*PConstants {
	if x != nil {
		return x.PluginConstant
	}
	return nil
}

type PAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Type        string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	VRule       string `protobuf:"bytes,5,opt,name=VRule,proto3" json:"VRule,omitempty"`
	VMsg        string `protobuf:"bytes,6,opt,name=VMsg,proto3" json:"VMsg,omitempty"`
}

func (x *PAttributes) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PAttributes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PAttributes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PAttributes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PAttributes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PAttributes) GetVRule() string {
	if x != nil {
		return x.VRule
	}
	return ""
}

func (x *PAttributes) GetVMsg() string {
	if x != nil {
		return x.VMsg
	}
	return ""
}

type PConstants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *PConstants) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PConstants) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PConstants) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// go:plugin type=plugin version=1
type VCode interface {
	ConfigPluginInfo(context.Context, emptypb.Empty) (PluginInfo, error)
	SendVerificationCode(context.Context, SendVerificationCodeRequest) (SendVerificationCodeResponse, error)
}
