//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.7
// source: VCodePlugin.proto

package pvcode

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const VCodePluginAPIVersion = 1

//export v_code_api_version
func _v_code_api_version() uint64 {
	return VCodePluginAPIVersion
}

var vCode VCode

func RegisterVCode(p VCode) {
	vCode = p
}

//export v_code_send_verification_code
func _v_code_send_verification_code(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req SendVerificationCodeRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := vCode.SendVerificationCode(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
